
-- USE sayKorean;

INSERT INTO genre (genreName) VALUES
('일상회화'),
('현대사회'),
('미디어'),
('KPOP'),
('전통'),
('디지털'),
('방언');

INSERT INTO users
  (name, email, password, nickName, phone, signupMethod, userState)
VALUES
('홍길동', 'user01@example.com', 'pass#01!', '토돌이', '+8201012340001', 1, 1),
('김영희', 'user02@example.com', 'pass#02!', '영희', '+8201012340002', 2, 1),
('John Smith', 'user03@example.com', 'pass#03!', 'john', '+8201012340003', 3, 1),
('田中太郎', 'user04@example.com', 'pass#04!', 'たなか', '+8201012340004', 1, 1),
('王伟', 'user05@example.com', 'pass#05!', 'wang', '+8201012340005', 4, 1),
('María López', 'user06@example.com', 'pass#06!', 'maria', '+8201012340006', 2, 1),
('Alice Kim', 'user07@example.com', 'pass#07!', 'alice', '+8201012340007', 3, 1),
('이수민', 'user08@example.com', 'pass#08!', '수민', '+8201012340008', 1, 1),
('박준호', 'user09@example.com', 'pass#09!', '준호', '+8201012340009', 2, 1),
('김민지', 'user10@example.com', 'pass#10!', '민지', '+8201012340010', 3, 1),

('Sara Park', 'user11@example.com', 'pass#11!', 'sara', '+8201012340011', 4, 1),
('佐藤花子', 'user12@example.com', 'pass#12!', 'はなこ', '+8201012340012', 1, 1),
('Li Wei', 'user13@example.com', 'pass#13!', 'liwei', '+8201012340013', 2, 1),
('Carlos Ruiz', 'user14@example.com', 'pass#14!', 'carlos', '+8201012340014', 3, 1),
('최유진', 'user15@example.com', 'pass#15!', '유진', '+8201012340015', 1, 1),
('정하늘', 'user16@example.com', 'pass#16!', '하늘', '+8201012340016', 2, 1),
('김도윤', 'user17@example.com', 'pass#17!', '도윤', '+8201012340017', 3, 1),
('Olivia Lee', 'user18@example.com', 'pass#18!', 'olivia', '+8201012340018', 4, 1),
('Daniel Choi', 'user19@example.com', 'pass#19!', 'daniel', '+8201012340019', 1, 1),
('박서연', 'user20@example.com', 'pass#20!', '서연', '+8201012340020', 2, 1),

('김하준', 'user21@example.com', 'pass#21!', '하준', '+8201012340021', 3, 1),
('이아린', 'user22@example.com', 'pass#22!', '아린', '+8201012340022', 4, 1),
('Noah Kim', 'user23@example.com', 'pass#23!', 'noah', '+8201012340023', 1, 1),
('Emma Park', 'user24@example.com', 'pass#24!', 'emma', '+8201012340024', 2, 1),
('Sophia Cho', 'user25@example.com', 'pass#25!', 'sophia', '+8201012340025', 3, 1),
('Mason Han', 'user26@example.com', 'pass#26!', 'mason', '+8201012340026', 4, 1),
('김지후', 'user27@example.com', 'pass#27!', '지후', '+8201012340027', 1, 1),
('이서윤', 'user28@example.com', 'pass#28!', '서윤', '+8201012340028', 2, 1),
('박민서', 'user29@example.com', 'pass#29!', '민서', '+8201012340029', 3, 1),
('한예린', 'user30@example.com', 'pass#30!', '예린', '+8201012340030', 4, 1);


INSERT INTO study
  ( themeKo, themeJp, themeCn, themeEn, themeEs,
   commenKo, commenJp, commenCn, commenEn, commenEs, genreNo)
VALUES
('안부 묻기','安否を尋ねる','问好','ask after','preguntar cómo le va',
 '지금 바빠? 라는 말은 나를 도와줄 수 있냐는 뜻이 되기도 합니다.',
 'むやみにごめんなさいと言ったら、本当に申し訳なくなる状況になるかもしれません。',
 '在韩国，有一种文化是照顾与我关系不亲近的他人，这叫礼仪。',
 'In Korea, people who want to talk to someone they are new to on the street may think of as a cult preacher.',
 'En Corea, se puede pensar que una persona que intenta hablar con una persona desconocida en la calle es un falso evangelista.',
 1),

('약속','アポ','约定','Promise','Promesa',
 '새로운 약속 날짜를 잡지 않고 약속을 미룬다고요? 다음 약속은 없습니다.',
 '今度ご飯を食べようという言葉が、本当にお米を食べようという意味ではないかもしれません。',
 '不安排新的约会日期而推迟约会吗？ 没有下一个约会。',
 'Postpone an appointment without setting a new date? There is no next appointment.',
 '¿Retrasará la cita sin fijar una nueva fecha? No tenemos la próxima cita.',
 1),

('식당에서','食堂で','在食堂里','In the dining room','en un restaurante',
 '알바생도 사장님이라고 부르세요. 국룰입니다.',
 '似たような食文化を持っていますが、韓国料理は大多数辛いです。',
 '餐厅不是为了当国王而去吃饭的地方，而是有礼貌地去吃饭的地方。',
 'Compared to the Anglo-American region, you can have delicious meals focused on vitamins and minerals at a lower price.',
 'Llámame jefe hasta un trabajador a tiempo parcial. A los coreanos les gusta.',
 1),

('내 상황 표현하기','自分の状況を表現する','表达我的情况','Expressing my situation','Expresión de mi situación',
 '옛날에는 표현하지 않는 것이 멋이었지만, 요즘은 솔직하게 문제를 말하는 문화가 자리잡혀있습니다.',
 '自分の状況について話すことが、日本よりは自由です',
 '中国人的比喻在韩国可能会好坏参半。',
 'As much as in the Anglo-American world, it is taboo to express your condition honestly.',
 'Es mejor hablar de alrededor que hablar directamente.',
 1),

('학교에서','学校で','在学校','At school','En la escuela',
 '21세기 대한민국 학교에서는 공부를 잘하는 것만이 살 길입니다.',
 '日本人ほどではありませんが、いじめ文化が残っている学校もあります',
 '有传闻说中国留学生把啤酒当饮料喝。',
 'Rest assured. Korea is a country without school gun problems.',
 'Pueden estar seguros de que Corea es un país libre de armas en la escuela.',
 2),

('회사에서','会社で','在公司','in a company','en la compañía',
 '취업난을 이기고 취칙하셨나요? 축하드립니다. 이제부터 동료와 선배들의 호감을 살 수 있는 언어를 배워봅시다.',
 '安心してください。社畜文化はありません。',
 '虽然中国赶超了很多,但在韩国企业文化中,业绩评价的重要性要高得多。',
 'Global corporate culture and Korean corporate culture can be quite different.',
 'La cultura corporativa global y la cultura corporativa coreana puede ser muy diferente.',
 2),

('미디어 관람','メディア観覧時','媒体观览时','When viewing media','cuando vemos los medios',
 '정말 사랑하는 TV 프로그램은 본방, 재방, 삼방까지 챙겨보곤 했었습니다.',
 '大好きなテレビ番組は、本番、再放送、三放送まで見ていました。',
 '非常喜爱的电视节目经常看首播、重播、三播。',
 'I used to watch TV programs that I really love, including the actual broadcast, rerun, and the third broadcast.',
 'Solía ver programas de televisión muy queridos en directo, repetición, trípode.',
 3),

('영화 감상평','映画鑑賞評','电影观后感','movie review','crítica de cine',
 '한국의 영화 산업이 정체되고 있지만, 여전히 한국 영화는 글로벌 시장에서 인정받고 있습니다.',
 '韓国の映画産業は停滞していますが、依然として韓国映画はグローバル市場で認められています。',
 '虽然韩国电影产业停滞不前，但韩国电影仍被全球市场认可。',
 'Although the Korean film industry is stagnating, Korean films are still recognized in the global market.',
 'Aunque la industria cinematográfica coreana se está estancando, las películas coreanas siguen siendo reconocidas en el mercado global.',
 3),

('OTT 감상평','ネットフリックスの感想','Netflix观后感','OTT Service Review','Evaluación del servicio de la OTT',
 '안방 극장''이라는 말이 OTT 산업의 확장으로 완벽하게 자리잡았습니다.',
 '「お茶の間劇場」という言葉がOTT産業の拡張で完璧に定着しました。',
 '"家庭剧场"一词完美地成为了OTT产业的扩张。',
 'The term ''bedroom theater'' has been perfectly established with the expansion of the OTT industry.',
 'El término "teatro de seguridad" se ha consolidado perfectamente con la expansión de la industria de la OTT.',
 3),

('음악 감상','音楽鑑賞','欣赏音乐','Listening to music','apreciación de la música',
 '한국인과 친해지고 싶다면 좋아하는 음악 장르를 물어보세요. 입덕시키려고 할 지도 모릅니다.',
 '韓国人と親しくなりたいなら、好きな音楽ジャンルを聞いてみてください。 ファンにさせようとするかもしれません。',
 '如果想和韩国人亲近，可以问一下喜欢的音乐类型。 说不定想让他入粉呢。',
 'If you want to be close to Koreans, ask them about their favorite music genre. They may try to make you a fan.',
 'Si quieres acercarte a los coreanos, pregúntale qué tipo de música te gusta. y luego tratar de ser parte de ella.',
 4),

('콘서트장에서','コンサート会場で','在演唱会现场','At the concert','en una sala de conciertos',
 '콘서트는 티케팅이 정말 중요합니다. 기둥 뒤에서 좋아하는 가수를 보고 싶지 않다면 말이죠.',
 'コンサートはチケッティングが本当に重要です。 柱の後ろで好きな歌手を見たくなければですね。',
 '演唱会抢票真的很重要。 如果不想在柱子后面看到喜欢的歌手的话。',
 'Tickets are really important for concerts, unless you want to see your favorite singer behind the pillar.',
 'Los boletos para un concierto son muy importantes. si no quieres ver a tu cantante favorito detrás de la columna.',
 4),

('새해 명절','新年の節句','新春佳节','New Year''s Day','festividad del Año Nuevo',
 '전통 문화는 바쁜 현대 사회 한국인들이 친척을 만날 수 있는 좋은 구실이 되어줍니다.',
 '伝統文化は忙しい現代社会の韓国人が親戚に会える良い役割を果たしてくれます。',
 '传统文化成为忙碌的现代社会韩国人见亲的好借口。',
 'Traditional culture is a good excuse for busy modern society Koreans to meet relatives.',
 'La cultura tradicional es un buen pretexto para que los coreanos de la sociedad moderna ocupados puedan conocer a sus parientes.',
 5),

('속담','諺','常言','proverb','proverbio',
 '한국인들은 옛 성현들의 지혜를 고스란히 간직하고 있습니다.',
 '韓国人は昔の聖賢の知恵をそのまま秘めています。',
 '韩国人保留了古代圣贤们的智慧。',
 'Koreans retain the wisdom of the old sages.',
 'Los coreanos conservan la sabiduría de sus antepasados.',
 5),

('줄임말','略語','缩略语','abbreviation','abreviación',
 '세기말에 디지털 혁명을 이뤄낸 한국인들은, 빠른 의사소통을 위해 줄임말을 즐겨 썼습니다.',
 '世紀末にデジタル革命を成し遂げた韓国人は、早いコミュニケーションのために略語を好んで使いました。',
 '世纪末实现数字革命的韩国人,为了快速沟通,喜欢使用缩略语。',
 'Koreans, who achieved the digital revolution at the end of the century, used abbreviations to communicate quickly.',
 'Los coreanos que lograron la revolución digital a finales del siglo disfrutaron usando abreviaturas para la comunicación rápida.',
 6),

('온라인에서','オンラインで','在线','online','en línea',
 '디지털 혁명 이후 인터넷 커뮤니티가 활발하게 운영되었습니다. 좋은 건지 나쁜 건지 애매하지만요 ㅎㅎ',
 'デジタル革命以来、インターネット コミュニティは活発に運営されてきました。 良いのか悪いのか曖昧ですが',
 '数字革命之后，互联网社区蓬勃发展。 是好是坏有点暧昧。',
 'The Internet community has been actively operating since the digital revolution. It''s ambiguous whether it''s good or bad. lol',
 'Desde la revolución digital, la comunidad de Internet ha funcionado activamente. si eso es bueno o malo.',
 6),

('방언 안부 묻기','方言の安否を問う','问候','in dialect','pregunta en dialecto',
 '지방 한국인들의 억양이 강하다고 해서 오해하지마세요. 친근함의 표시일 수도 있습니다.',
 '地方の韓国人のイントネーションが強いからといって誤解しないでください。 親しみの表れかもしれません。',
 '不要因为地方韩国人的口音太重而误会。 也可能是亲切的表示。',
 'Don''t get me wrong because local Koreans have strong accents. It can be a sign of friendliness.',
 'No me malinterpreten porque los coreanos locales tienen un fuerte acento. Podría ser un signo de familiaridad.',
 7),

('방언 인사말','方言のあいさつ','客套话','a dialect greeting','saludo dialéctico',
 '한국에는 지역 별로 다른 인사말들이 있지만, 근간은 타인의 안녕을 빌어주는 의미를 담고 있습니다.',
 '韓国には地域ごとに違う挨拶がありますが、根幹は他人の安寧を祈る意味が込められています。',
 '虽然韩国各地区有不同的问候语,但最近包含了祈求他人安宁的意义。',
 'In Korea, there are different greetings from region to region, but the basis is to pray for the well-being of others.',
 'En Corea hay diferentes saludos de cada región, pero la base tiene el significado de desear el bienestar de los demás.',
 7);




 INSERT INTO exam
  (examKo, examRoman, examJp, examCn, examEn, examEs, imageName, imagePath, studyNo)
VALUES
('배고파 죽겠다.','baegopa jukgetda.','お腹すいて死にそう。','饿死了。','I’m starving.','Me muero de hambre.','1_img','',4),
('괜찮아?','gwaenchanha?','大丈夫？','你没事吧？','Are you okay?','¿Estás bien?','2_img','',1),
('지금 바빠?','jigeum bappa?','今忙しい？','你现在忙吗？','Are you busy now?','¿Estás ocupado ahora?','3_img','',1),
('잠깐만요.','jamkkanmanyo.','ちょっと待ってください。','请稍等。','Just a moment, please.','Un momento, por favor.','4_img','',4),
('잠깐 쉬자.','jamkkan swija.','ちょっと休もう。','休息一下吧。','Let’s take a short break.','Tomemos un descanso.','5_img','',4),
('자리 있나요?','jari itnayo?','席は空いてますか？','有座位吗？','Do you have any seats available?','¿Hay sitio?','6_img','',3),
('영수증 필요해요.','yeongsujeung piryohaeyo.','領収書が必要です。','我需要收据。','I need a receipt, please.','Necesito el recibo.','7_img','',3),
('다음에 같이 가자.','daeume gachi gaja.','今度一緒に行こう。','下次一起去吧。','Let’s go together next time.','Vamos juntos la próxima vez.','8_img','',2),
('시간 되면 전화해.','sigan doemyeon jeonhwahae.','時間あったら電話して。','有时间给我打电话。','Call me when you have time.','Llámame cuando tengas tiempo.','9_img','',2),
('오늘은 쉬고 싶어.','oneureun swigo sipeo.','今日は休みたい。','我今天想休息。','I want to rest today.','Hoy quiero descansar.','','',2),
('약속, 다음 주로 미루자.','yaksok, daeum juro miruja.','約束は来週に延ばそう。','约定改到下周吧。','Let’s reschedule for next week.','Aplacemos la cita para la próxima semana.','','',2),
('생각해 보고 연락할게.','saenggakhae bogo yeollakhalge.','考えてから連絡するね。','我想一想再联系你。','I’ll think it over and get back to you.','Lo pensaré y te contacto.','','',2),
('추천 메뉴가 뭐예요?','chucheon menyuga mwoyeyo?','おすすめのメニューは何ですか。','有什么推荐的吗？','What do you recommend here?','¿Cuál es el plato recomendado?','13_img','',3),
('주소 좀 보내 주세요.','juso jom bonae juseyo.','住所を送ってください。','请把地址发给我。','Please send me the address.','Por favor, envíame la dirección.','','',2),
('출석 불러요.','chulseok bulleoyo.','出席を取りましょう。','开始点名吧。','Let’s take attendance.','Voy a pasar lista.','15_img','',5),
('과제 끝났어?','gwaje kkeunnasseo?','宿題終わった？','作业做完了吗？','Did you finish the assignment?','¿Terminaste la tarea?','','',5),
('회의 시작하죠.','hoeui sijakhajyo.','会議を始めましょう。','我们开始开会吧。','Let’s start the meeting.','Comencemos la reunión.','','',6),
('보고서 제출해요.','bogoseo jechulhaeyo.','レポートを提出してください。','请提交报告。','Please submit the report.','Entrega el informe.','18_img','',6),
('점심 회식이야.','jeomsim hoesigiya.','昼は会食だよ。','中午聚餐。','We have a team lunch.','Tenemos comida de equipo.','','',6),
('휴가 쓸게요.','hyuga sseulgeyo.','休みを取ります。','我要请假。','I’m going to take a day off.','Voy a tomar vacaciones.','20_img','',6),
('오늘 발표라 좀 긴장돼.','oneul balpyora jom ginjangdwae.','今日発表でちょっと緊張してる。','今天要发表，有点紧张。','I have a presentation today, so I’m a bit nervous.','Estoy un poco nervioso por la presentación de hoy.','21_img','',6),
('출퇴근이 너무 길어.','chultoegeuni neomu gireo.','通勤時間が長すぎる。','通勤时间太长了。','My commute is too long.','El trayecto al trabajo es demasiado largo.','22_img','',6),
('팀 바뀌었어.','tim bakkwieosseo.','チーム変わった。','我换组了。','I switched teams.','Cambié de equipo.','','',6),
('예고편 봤어?','yegopyeon bwasseo?','予告編見た？','看预告片了吗？','Did you watch the trailer?','¿Viste el tráiler?','','',7),
('몰아보기 하자.','morabogi haja.','一気見しよう。','我们一口气看吧。','Let’s binge-watch.','Vamos a mirar la serie en sucesión','','',7),
('자막 켜 줘.','jamak kyeo jwo.','字幕つけて。','把字幕打开。','Turn on the subtitles.','Pon los subtítulos.','','',7),
('실시간이야.','silsiganiya.','リアルタイムだよ。','正在直播。','It’s live.','Es en vivo.','','',7),
('엔딩 미쳤다.','ending michyeotda.','エンディングやばかった。','结局太炸了。','The ending was insane.','El final fue una locura.','','',7),
('스포 금지!','seupo geumji!','ネタバレ禁止！','别剧透！','No spoilers!','¡Es prohibido hacer spoilers!','','',9),
('몇 화까지 있어?','myeot hwa kkaji isseo?','何話まである？','一共有几集？','How many episodes are there?','¿Cuántos episodios hay?','','',9),
('1화부터 재밌다','1hwa buteo jaemitda','1話から面白い。','从第一集就好看。','It’s good from episode 1.','Es interesante desde el primer episodio.','','',9),
('감독이 누구야?','gamdogi nuguya?','監督は誰？','导演是谁？','Who’s the director?','¿Quién es el director?','','',8),
('몰입이 잘 돼','moribi jal dwae','没入感が高い。','代入感很强。','It’s really immersive.','Es muy inmersivo.','','',8),
('여운이 길게 남는 작품이야.','yeouni gilge namneun jakpumiya.','余韻が長く残る作品だよ。','是一部让人回味很久的作品。','It stays with you for a long time.','Es una obra que deja una gran impresión.','','',8),
('연출이 대단해','yeonchuri daedanhae','演出がすごい。','导演功力很强。','The direction is outstanding.','La dirección es increíble.','','',8),
('출연진이 마음에 들어','chulyeonjini maeume deureo','キャストが気に入った。','我很喜欢演员阵容。','I like the cast.','Me gusta el elenco.','','',8),
('목소리가 너무 좋아','mogsoriga neomu joha','声がめっちゃ好き。','声音太好听了。','I love their voice.','me gusta tu voz.','','',10),
('안무가 멋있어','anmuga meosisseo','振り付けがかっこいい。','编舞很帅。','The choreography is awesome.','La coreografía es genial.','','',10),
('콘서트 언제래?','konseoteu eonjerae?','コンサートいつ？','演唱会什么时候？','When’s the concert?','¿Cuándo es el concierto?','','',10),
('신곡 나왔대','singok nawatdae','新曲出たって。','听说新歌出了。','The new song just dropped.','Sacaron una nueva canción.','','',10),
('노래 좋다','norae jota','この曲いいね。','这首歌真好听。','I like this song.','Me gusta la canción.','41_img','',10),
('가사가 마음에 들어','gasaga maeume deureo','歌詞が気に入った。','我很喜欢歌词。','I like the lyrics.','Me gustan las letras.','','',10),
('정규 앨범이야','jeonggyu aelbeomiya','フルアルバムだよ。','是正式专辑。','It’s a full-length album.','Es un álbum completo.','','',10),
('티켓팅이 너무 치열했어','tikettingi neomu chiyeolhaesseo','チケット取りが激戦だった。','票太难抢了。','Ticketing was brutal.','Fue muy difícil conseguir entradas.','','',11),
('응원법 있지?','eungwonbeop itji?','掛け声あるよね？','有应援口号吧？','There’s a fanchant, right?','¿Hay una guía de fan chants?','45_img','',11),
('떡국 먹자.','tteokguk meokja.','トッククを食べよう。','吃年糕汤吧。','Let’s eat tteokguk.','Comamos tteokguk.','46_img','',12),
('한복 예쁘다.','hanbok yeppeuda.','ハンボクきれい。','韩服真好看。','That hanbok is beautiful.','El hanbok es bonito.','47_img','',12),
('새해 복 많이 받아','saehae bok manhi bada','明けおめ！','新年快乐！','Happy New Year!','¡Feliz año nuevo!','48_img','',12),
('세배했어?','sebaehaesseo?','新年のあいさつ、した？','拜年了吗？','Did you do sebae?','hiciste reverencia?', '49_img','…',12),
('윷놀이 하자.','yutnori haja.','ユンノリやろう。','玩掷柶吧。','Let’s play yutnori.','Juguemos yutnori.','50_img','',12),
('배움에는 때가 없다.','baeumeneun ttaega eopda.','学ぶのに遅すぎることはない。','学习任何时候都不晚。','It’s never too late to learn.','Nunca es tarde para aprender.','','',13),
('때가 되면 꽃은 핀다.','ttaega doemyeon kkocheun pinda.','時が来れば花は咲きます。','花到时自会开。','Everything blooms in its time.','Las flores florecen cuando es su tiempo.','','',13),
('하늘이 무너져도 솟아날 구멍이 있어.','haneuri muneojyeodo sosanal gumeongi isseo.','たとえ最悪でも活路はございます。','天无绝人之路。','There’s always a way out. / Every cloud has a silver lining.','Siempre hay una salida, incluso en las peores situaciones.','','',13),
('고생 끝에 낙이 온다.','gosaeng kkeute nagi onda.','苦あれば楽ありです。','苦尽甘来。','After hardship comes joy. / No pain, no gain.','Después del esfuerzo, viene la recompensa.','','',13),
('호랑이도 제 말 하면 온다더라.','horangido je mal hamyeon ondadeora.','噂をすれば影と申します。','说曹操，曹操到。','Speak of the devil.','Hablando del rey de Roma, por la puerta asoma.','','',13),
('존버 가자.','jonbeo gaja.','ガマンして持ちこたえよう。','咬牙坚持吧。','Let’s hold and endure. (HODL)','Aguanta hasta el final.','','',14),
('현타 왔다.','hyeonta watda.','現実に戻ったわ。','突然现实感袭来了。','Reality just hit me.','Tuve un momento de realidad.','','',14),
('ㅇㅋ, ㄱㄱ.','okei, gogo.','オケ、行こ。','OK，走起。','OK, let’s go.','Ok, vamos.','','',14),
('ㅋㅋ 대박.','kk daebak.','ｗｗ やば。','哈哈，太厉害了。','ol, that’s awesome.','Jajaja.','','',14),
('무지성','mujiseong','脳死で。','不加思考地。','Mindlessly.','Sin pensar','','',14),
('인증샷 올릴게.','injeungsyat ollilge.','証拠写真あげるね。','我发个认证照。','I’ll post a proof pic.','Subiré la foto de prueba.','','',15),
('제목 낚시 심하네.','jemok naksi simhane.','タイトル詐欺えぐいね。','标题党太过了。','That’s some serious clickbait.','El título fue puro clickbait.','','',15),
('TMI지만 공유할게.','TMIjiman gongyuhalge.','TMIだけど共有するね。','虽然有点TMI，但分享一下。','TMI, but I’ll share.','TMI, compartiré.','','',15),
('타임라인이 난장판이야.','taimraini nanjangpaniya.','タイムラインがカオス。','时间线一团糟。','My timeline is a mess.','Mi timeline está hecho un caos.','','',15),
('알고리즘이 나를 잘 알아.','algorijeumi nareul jal ara.','アルゴリズムが俺（私）を分かりすぎ。','算法太懂我了。','The algorithm knows me too well.','El algoritmo me conoce bien.','','',15),
('[부산] 밥 묵었나?','bab mugeonna?','ご飯食べた？','吃饭了吗？','[Busan] Have you eaten?','¿Has comido?','','',16),
('[대구] 뭐 하노?','mwo hano?','何してんの？','在干嘛？','[Daegu] What are you doing?','¿Qué haces?','','',16),
('[전라] 와그라냐?','wageuranya?','どうしたん？','怎么啦？','[Jeolla] What’s up? / What’s wrong?','¿Qué pasa?','','',17),
('[충청] 그랬슈?','geuraessyu?','そうなん？','这样啊？','[Chungcheong] Is that so? / Really?','¿Ah sí?','','',17),
('[인천] 어디 가냐?','eodi gan-ya?','どこ行くの？','去哪儿？','[Incheon] Where are you going?','¿A dónde vas?','','',16),
('[제주] 혼저 옵서예.','honjeo opseoye.','ようこそ。','欢迎光临','[Jeju] Welcome / Please come in.','Bienvenido.','','',16),
('[강원] 얼매요?','eolmaeyo?','いくら？','多少钱？','[Gangwon] How much is it?','¿Cuánto cuesta?','','',17),
('[전라] 거 참 말허덜 말어.','geo cham malheodeol maleo.','そういう言い方やめて。','别那样说。','[Jeolla] Don’t talk like that. / Stop saying that.','¿Hablas o no hablas?','','',17),
('[경상] 마, 그거 맞다 아이가.','ma, geugeo matda aiga.','おい、それで合ってるやろ。','那不就对了吗。','[Gyeongsang] Hey, that’s right, isn’t it.','¡Oye, eso es correcto!','','',17),
('[부산] 그라믄 됐데이.','geurameun dwaetdei.','じゃあ、それでええわ。','那就行。','[Busan] Then that’s fine. / That’ll do.','Entonces, está bien.','','',17);



INSERT INTO audio (audioName, audioPath, lang, examNo) VALUES
('1_kor_voice','',1,1),
('2_kor_voice','',1,2),
('3_kor_voice','',1,3),
('4_kor_voice','',1,4),
('5_kor_voice','',1,5),
('6_kor_voice','',1,6),
('7_kor_voice','',1,7),
('8_kor_voice','',1,8),
('9_kor_voice','',1,9),
('10_kor_voice','',1,10),
('11_kor_voice','',1,11),
('12_kor_voice','',1,12),
('13_kor_voice','',1,13),
('14_kor_voice','',1,14),
('15_kor_voice','',1,15),
('16_kor_voice','',1,16),
('17_kor_voice','',1,17),
('18_kor_voice','',1,18),
('19_kor_voice','',1,19),
('20_kor_voice','',1,20),
('21_kor_voice','',1,21),
('22_kor_voice','',1,22),
('23_kor_voice','',1,23),
('24_kor_voice','',1,24),
('25_kor_voice','',1,25),
('26_kor_voice','',1,26),
('27_kor_voice','',1,27),
('28_kor_voice','',1,28),
('29_kor_voice','',1,29),
('30_kor_voice','',1,30),
('31_kor_voice','',1,31),
('32_kor_voice','',1,32),
('33_kor_voice','',1,33),
('34_kor_voice','',1,34),
('35_kor_voice','',1,35),
('36_kor_voice','',1,36),
('37_kor_voice','',1,37),
('38_kor_voice','',1,38),
('39_kor_voice','',1,39),
('40_kor_voice','',1,40),
('41_kor_voice','',1,41),
('42_kor_voice','',1,42),
('43_kor_voice','',1,43),
('44_kor_voice','',1,44),
('45_kor_voice','',1,45),
('46_kor_voice','',1,46),
('47_kor_voice','',1,47),
('48_kor_voice','',1,48),
('49_kor_voice','',1,49),
('50_kor_voice','',1,50),
('51_kor_voice','',1,51),
('52_kor_voice','',1,52),
('53_kor_voice','',1,53),
('54_kor_voice','',1,54),
('55_kor_voice','',1,55),
('56_kor_voice','',1,56),
('57_kor_voice','',1,57),
('58_kor_voice','',1,58),
('59_kor_voice','',1,59),
('60_kor_voice','',1,60),
('61_kor_voice','',1,61),
('62_kor_voice','',1,62),
('63_kor_voice','',1,63),
('64_kor_voice','',1,64),
('65_kor_voice','',1,65);

INSERT INTO audio (audioName, audioPath, lang, examNo) VALUES
('1_eng_voice','',2,1),
('2_eng_voice','',2,2),
('3_eng_voice','',2,3),
('4_eng_voice','',2,4),
('5_eng_voice','',2,5),
('6_eng_voice','',2,6),
('7_eng_voice','',2,7),
('8_eng_voice','',2,8),
('9_eng_voice','',2,9),
('10_eng_voice','',2,10),
('11_eng_voice','',2,11),
('12_eng_voice','',2,12),
('13_eng_voice','',2,13),
('14_eng_voice','',2,14),
('15_eng_voice','',2,15),
('16_eng_voice','',2,16),
('17_eng_voice','',2,17),
('18_eng_voice','',2,18),
('19_eng_voice','',2,19),
('20_eng_voice','',2,20),
('21_eng_voice','',2,21),
('22_eng_voice','',2,22),
('23_eng_voice','',2,23),
('24_eng_voice','',2,24),
('25_eng_voice','',2,25),
('26_eng_voice','',2,26),
('27_eng_voice','',2,27),
('28_eng_voice','',2,28),
('29_eng_voice','',2,29),
('30_eng_voice','',2,30),
('31_eng_voice','',2,31),
('32_eng_voice','',2,32),
('33_eng_voice','',2,33),
('34_eng_voice','',2,34),
('35_eng_voice','',2,35),
('36_eng_voice','',2,36),
('37_eng_voice','',2,37),
('38_eng_voice','',2,38),
('39_eng_voice','',2,39),
('40_eng_voice','',2,40),
('41_eng_voice','',2,41),
('42_eng_voice','',2,42),
('43_eng_voice','',2,43),
('44_eng_voice','',2,44),
('45_eng_voice','',2,45),
('46_eng_voice','',2,46),
('47_eng_voice','',2,47),
('48_eng_voice','',2,48),
('49_eng_voice','',2,49),
('50_eng_voice','',2,50),
('51_eng_voice','',2,51),
('52_eng_voice','',2,52),
('53_eng_voice','',2,53),
('54_eng_voice','',2,54),
('55_eng_voice','',2,55),
('56_eng_voice','',2,56),
('57_eng_voice','',2,57),
('58_eng_voice','',2,58),
('59_eng_voice','',2,59),
('60_eng_voice','',2,60),
('61_eng_voice','',2,61),
('62_eng_voice','',2,62),
('63_eng_voice','',2,63),
('64_eng_voice','',2,64),
('65_eng_voice','',2,65),
('66_eng_voice','',2,66),
('67_eng_voice','',2,67),
('68_eng_voice','',2,68),
('69_eng_voice','',2,69),
('70_eng_voice','',2,70),
('71_eng_voice','',2,71),
('72_eng_voice','',2,72),
('73_eng_voice','',2,73),
('74_eng_voice','',2,74),
('75_eng_voice','',2,75);



INSERT INTO attendance (attenDate, attendDay, userNo) VALUES
('2025-08-01','2025-08-01', 1),
('2025-08-01','2025-08-01', 2),
('2025-08-02','2025-08-02', 1),
('2025-08-03','2025-08-03', 3),
('2025-08-03','2025-08-03', 2),
('2025-08-03','2025-08-04', 4),
('2025-08-03','2025-08-03', 1),
('2025-08-04','2025-08-04', 5),
('2025-08-05','2025-08-05', 2),
('2025-08-05','2025-08-05', 1);


-- USE sayKorean;



-- [test 테이블 11개 샘플]
INSERT INTO test (testTitle, studyNo) VALUES
('인사 표현 익히기', 1),
('약속 잡기 연습', 2),
('식당 주문 대화', 3),
('길 안내 요청', 4),
('날씨 묻고 답하기', 5),
('취미 이야기', 6),
('가족 소개하기', 7),
('쇼핑 회화', 8),
('전화 대화', 9),
('병원 방문 표현', 10),
('교통 이용하기', 11);

INSERT INTO testItem (question, examNo, testNo) VALUES
('그림: 올바른 인사 표현을 고르세요.', 1, 1),
('음성: 약속 시간에 맞는 답변을 고르세요.', 2, 2),
('주관식: 식당에서 주문할 때 사용할 문장을 작성하세요.', 3, 3),
('그림: 길을 묻는 올바른 표현을 선택하세요.', 4, 4),
('음성: 날씨를 묻는 표현으로 올바른 것은?', 5, 5),
('주관식: 취미를 묻는 질문을 한국어로 작성하세요.', 6, 6),
('그림: 가족을 소개하는 올바른 문장을 고르세요.', 7, 7),
('음성: 쇼핑 상황에서 맞는 문장을 선택하세요.', 8, 8),
('주관식: 전화 인사말을 작성하세요.', 9, 9),
('그림: 병원에서 쓸 수 있는 표현을 고르세요.', 10, 10),
('음성: 교통 안내 표현 중 맞는 것을 고르세요.', 11, 11);


INSERT INTO ranking (testRound, userAnswer, isCorrect, resultDate, testItemNo, userNo) VALUES
(1, '객관식 문항이거나 공란으로 제출했습니다.', 1, '2025-10-16', 1, 1),
(1, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 2, 2),
(1, '안녕하세요', 1, '2025-10-16', 3, 3),
(1, '죄송합니다', 1, '2025-10-16', 4, 4),
(2, '오늘 날씨가 좋네요', 1, '2025-10-16', 5, 5),
(2, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 6, 6),
(2, '감사합니다', 1, '2025-10-16', 7, 7),
(2, '반갑습니다', -1, '2025-10-16', 8, 8),
(3, '잘 지냈습니까?', 1, '2025-10-16', 9, 9),
(3, '객관식 문항이거나 공란으로 제출했습니다.', 1, '2025-10-16', 10, 10),
(3, '네, 맞습니다', 1, '2025-10-16', 11, 11),
(3, '아닙니다', -1, '2025-10-16', 1, 12),
(4, '죄송합니다', 1, '2025-10-16', 2, 13),
(4, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 3, 14),
(4, '좋아요', 1, '2025-10-16', 4, 15),
(5, '네, 좋아요', 1, '2025-10-16', 5, 1),
(5, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 6, 2),
(5, '괜찮습니다', 1, '2025-10-16', 7, 3),
(5, '그럼요', -1, '2025-10-16', 8, 4),
(6, '정답입니다', 1, '2025-10-16', 9, 5),
(6, '객관식 문항이거나 공란으로 제출했습니다.', 1, '2025-10-16', 10, 6),
(6, '좋은 하루입니다', -1, '2025-10-16', 11, 7),
(7, '감사합니다', 1, '2025-10-16', 1, 8),
(7, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 2, 9),
(8, '안녕히 가세요', 1, '2025-10-16', 3, 10),
(8, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 4, 11),
(9, '축하합니다', 1, '2025-10-16', 5, 12),
(9, '잘했습니다', 1, '2025-10-16', 6, 13),
(10, '수고하셨습니다', 1, '2025-10-16', 7, 14),
(10, '객관식 문항이거나 공란으로 제출했습니다.', -1, '2025-10-16', 8, 15);


INSERT INTO loading (loadTitle, loadInfo, loadFileName) VALUES
('숭례문', '남대문이라고도 불립니다', '1_load_img'),
('북촌한옥마을', '외국인들이 더 많은 곳입니다', '2_load_img'),
('국립중앙박물관', '요즘 핫합니다', '3_load_img'),
('경복궁', '조선의 대표 궁궐입니다', '4_load_img'),
('창덕궁', '비원으로 유명합니다', '5_load_img'),
('덕수궁', '도심 속 궁궐로 인기 있습니다', '6_load_img'),
('남산타워', '야경이 아름답습니다', '7_load_img'),
('광화문', '서울의 중심입니다', '8_load_img'),
('한강공원', '서울 시민들의 쉼터입니다', '9_load_img'),
('롯데월드', '아이들에게 인기 많은 테마파크입니다', '10_load_img'),
('코엑스', '국제 박람회가 자주 열립니다', '11_load_img'),
('63빌딩', '한강 전망이 멋진 곳입니다', '12_load_img'),
('홍대거리', '젊음의 거리로 유명합니다', '13_load_img'),
('명동', '쇼핑의 메카입니다', '14_load_img'),
('이태원', '다문화 거리로 유명합니다', '15_load_img'),
('잠실야구장', '야구 팬들의 성지입니다', '16_load_img'),
('서울숲', '산책하기 좋은 공원입니다', '17_load_img'),
('청계천', '도심 속 힐링 장소입니다', '18_load_img'),
('남이섬', '자연이 아름다운 여행지입니다', '19_load_img'),
('가로수길', '감성 카페가 많은 거리입니다', '20_load_img'),
('DDP', '현대적 건축미가 돋보이는 공간입니다', '21_load_img'),
('국립과학관', '아이들과 함께하기 좋습니다', '22_load_img'),
('올림픽공원', '자전거 타기 좋은 장소입니다', '23_load_img'),
('서울대공원', '동물원과 식물원이 있습니다', '24_load_img'),
('북한산', '등산 명소로 유명합니다', '25_load_img'),
('남산공원', '케이블카 타고 올라갈 수 있습니다', '26_load_img'),
('경희궁', '조선시대 다섯 궁 중 하나입니다', '27_load_img'),
('롯데타워', '서울의 랜드마크입니다', '28_load_img'),
('광장시장', '빈대떡으로 유명한 전통시장입니다', '29_load_img'),
('서울시청', '시민들의 행정 중심지입니다', '30_load_img');

select * from users;
select * from attendance;